NEW_YORK_ARTICLE_PAGE_CLONE
Lidya1234/NEW_YORK_TIMES_ARTICLE pull request #1
Opened 2020-08-20 15:29 UTC by Lidya1234

This site is the clone of New York Times article. It has three sections the navigation bar, main (with five sections inside it) and a footer. There are links which mimics the real website but they do not function.

2020-08-20 18:50 UTC, SafaErden requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, your project is awesome 😄 it really looks exactly like the original. It has both nav and footer in a fixed position 👐 , However, we need a little fix before we can proceed. Kindly find comments below:

<hr>

- [ ] Your page should have an expandable footer with fixed position (it sticks to the bottom part of the screen, you may not see it if you are logged in) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

![image](https://user-images.githubusercontent.com/60184961/90810959-7937fd00-e32c-11ea-9112-e94a80d38cdd.png)

- [ ] Kindly remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. ([Check this link form better understanding Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

**_NOTES:_**

- Your PR should have a meaningful title and a brief description. In this case, your PR does not have a meaningful title. Please consider this issue for your upcoming projects.

<hr>

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

<hr>

Kindly make these changes and submit another code review 👌
Happy coding_ 👨‍💻

2020-08-20 18:50 UTC, SafaErden commented on index.html
> +
Please avoid using redundant empty lines between tags and avoid using extra indentation (2 spaces suggested for each indentation). To provide this, I can suggest you to install the proper code-formatter plugins.

2020-08-20 18:50 UTC, SafaErden commented on index.html
> +    <section class="section-1">
- [OPTIONAL] Please consider the use of the `<main>` tag for the dominant content of the `<body>` of a document, you can wrap the dominant content with the `<main>` tag

2020-08-20 18:50 UTC, SafaErden commented on index.html
> +            </div>
- [ ]  Please center the elements to have the same UI with the original page( the content is aligned left in your project):

![image](https://user-images.githubusercontent.com/60184961/90810097-1d20a900-e32b-11ea-8e61-c297afc67991.png)

2020-08-20 18:50 UTC, SafaErden commented on index.html
> +    </section>
- [ ] Please do not use screenshots of the original page as shortcut to bypass requirements. Please create the 'theory of inflation' section by using grid, flex of float both for images and texts (If you want to use a background image like it is used in the original page, then the view should not be broken in different screen sizes like it is in the original page.)

![image](https://user-images.githubusercontent.com/60184961/90810422-9b7d4b00-e32b-11ea-8035-8c111f331548.png)

2020-08-20 18:50 UTC, SafaErden commented on README.md
> +Additional description about the project and its features.
- [ ] If this line is a title, please make it has the same style with the other titles in your README.

2020-08-20 18:50 UTC, SafaErden commented on README.md
> +To get a local copy up and running follow these simple example steps.
- [ ] I couldn't see the simple steps that you are talking about 😄

2020-08-22 10:08 UTC, ikraamg commented
### **Status: PROJECT APPROVED**  :1st_place_medal: :1st_place_medal: :1st_place_medal:

Hi @Lidya1234  and @Abhigyan001  :smile:  Congratulations, your project looks really good and you did an amazing job making the necessary changes :sunglasses:. 

Before you merge and submit your project, please change your live link. It does not reflect your latest changes. 

_**Happy coding and good luck on the next project**_  :desktop_computer: 

_Project reviewed by Ikraam Ghoor (TSE)_

2020-08-24 07:43 UTC, merged